"""Update reviews table

Revision ID: 26e110546008
Revises: daf5ad5c14f3
Create Date: 2025-04-14 16:38:20.008688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26e110546008'
down_revision: Union[str, None] = 'daf5ad5c14f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE reviews
        ALTER COLUMN rating TYPE INTEGER USING rating::integer;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE reviews
        ALTER COLUMN rating TYPE VARCHAR USING rating::text;
        """
    )
    # ### end Alembic commands ###
